// src/config/club-constants.ts

export const CLUB_PRESIDENT_NAME_STORAGE_KEY = 'TRAPEL_FC_CLUB_PRESIDENT_NAME';
export const CLUB_ADDRESS_STORAGE_KEY = 'TRAPEL_FC_CLUB_ADDRESS';
export const CLUB_SIRET_STORAGE_KEY = 'TRAPEL_FC_CLUB_SIRET';
export const CLUB_EMAIL_STORAGE_KEY = 'TRAPEL_FC_CLUB_EMAIL';
export const CLUB_FFF_AFFILIATION_STORAGE_KEY = 'TRAPEL_FC_CLUB_FFF_AFFILIATION';
